### ISSUE TITLE
Use es6 Arrow functions without using return keyword

### ISSUE THREAD

**Issue by nishant-jain-94** [sro-boeing-wave-2/remove-duplicate-items-js-problem-saikiran290695#1]
https://github.com/sro-boeing-wave-2/remove-duplicate-items-js-problem-saikiran290695/blob/817ebed8e45ff866cfb9a9066209046dfe9c86d5/index.js#L6-L9

**Comment by nishant-jain-94** [comment]
Arrow functions can be referred here from https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions

**Comment by saikiran290695** [comment]
Modified arrow function to one line code, without return statement
